//user
export const IS_LOGGED = 'IS_LOGGED'
export const USER_INFO = 'USER_INFO'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'

//posts
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const GET_POSTS_BY_GROUP = 'GET_POSTS_BY_GROUP'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

//groups
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS'
export const GET_ALL_GROUPS_FAIL = 'GET_ALL_GROUPS_FAIL'
export const GET_ALL_GROUPS_PROGRESS = 'GET_ALL_GROUPS_PROGRESS'

export const GET_GROUP_BY_ID_SUCCESS = 'GET_GROUP_BY_ID_SUCCESS'
export const GET_GROUP_BY_ID_FAIL = 'GET_GROUP_BY_ID_FAIL'
export const GET_GROUP_BY_ID_PROGRESS = 'GET_GROUP_BY_ID_PROGRESS'

export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'

//reaction
export const GET_REACTIONS_BY_POST_SUCCESS = 'GET_REACTIONS_BY_POST_SUCCESS'
export const GET_REACTIONS_BY_POST_FAIL = 'GET_REACTIONS_BY_POST_FAIL'
export const ADD_REACTION_SUCCESS = 'ADD_REACTION_SUCCESS'
export const ADD_REACTION_FAIL = 'ADD_REACTION_FAIL'
export const REMOVE_REACTION_SUCCESS = 'REMOVE_REACTION_SUCCESS'
export const REMOVE_REACTION_FAIL = 'REMOVE_REACTION_FAIL'
